### ISSUE TITLE
How to use with stack_trace

### ISSUE THREAD

**Issue by johnryan-wf** [dart-lang/source_map_stack_trace#1]
Is it possible to use source_map_stack_trace with a Trace parsed from [stack_trace](https://github.com/dart-lang/stack_trace)?  Here's my use case:
1. In Dartium, (and when the app is running in debug-mode,) use Chain.capture() to print the asynchronous stack chain.
2. In other browsers, use the source map and source_map_stack_trace to convert the trace to a native-looking stack trace.
3. In other browsers, when the app is in debug-mode, do both #1 and #2 to get a native-looking stack chain.

Side note: When we build our application, we use `--mode=release` but our pubspec sets `sourceMaps` to true for the dart2js transformer:

[Here's an example project](https://github.com/johnryan-wf/source_map_issue_example) that attempts to do this.  Note that the output in Chrome doesn't seem to be doing the right thing.

@nex3

**Comment by nex3** [comment]
For future reference, [StackOverflow](http://stackoverflow.com/tags/dart) is a better place to ask questions like this; the issue tracker is mostly for bug reports and feature requests.

The `Chain` class implements `StackTrace`, and `mapStackTrace()` knows how to handle it properly. If you change `main()` in your example to:

``` dart
main() async {
  var map = await getMapping();

  Chain.capture(() async {
    try {
      await throwAsyncException();
    } catch(e, stackTrace) {
      var mapped = mapStackTrace(map, stackTrace);
      print("Mapped trace:");
      print(mapped);
      rethrow;
    }
  }, onError: (err, Chain chain) {
    var cleaned = new Trace.from(mapStackTrace(map, chain));
    cleaned = cleaned.foldFrames(
        (frame) => frame.isCore,
        terse: true);
    print(cleaned);
  });
}
```

You'll get the mapped stack chain.
