### ISSUE TITLE
Migrate off of package_resolver and onto package_config

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/source_map_stack_trace#10]
This should provide all the same functionality now, and we are considering [deprecating package_resolver](https://github.com/dart-lang/package_resolver/issues/30).

**Comment by natebosch** [comment]
This will require a signature change so it will be breaking, but not too difficult to roll out.

**Comment by natebosch** [comment]
There is an open question about whether we need to support both `Map<String, Uri>` and packages directory style. The packages directory style argument is, I _think_, only used for the pub serve workflow which isn't currently supported in the test runner. I don't know whether it's safe to remove that support.

**Comment by jakemac53** [comment]
The `Map<String, Uri>` style can still support a `packages/` directory right? You could even implement map with something that builds the uris dynamically for any package name if you really wanted to.

**Comment by natebosch** [comment]
That's true, I think I'll run with that.

**Comment by jakemac53** [comment]
Going to go with the same strategy as (shelf_packages_handler)[https://github.com/dart-lang/shelf_packages_handler/pull/11] and change the api to accept a `Map<String, Uri>` of package names to the base uri to resolve `package:` uris for those packages.

That will hopefully allow us to drop the dependency entirely.
