### ISSUE TITLE
Dependency on dart:mirrors?

### ISSUE THREAD

**Issue by xvrh** [dart-lang/source_map_stack_trace#2]
Hello,
I use this library in my web application to de-minify the stacktraces of some uncaught exceptions.

Since the version 1.1.0, the dart2js compiler reports a warning because of a dependency on `dart:mirrors` with:
`package:source_map_stack_trace => package:package_resolver => package:http => dart:mirrors`

Is it possible to provide a mirrors-free version of this package?

**Comment by nex3** [comment]
This warning is bogus; it won't actually cause any problems in practice. See dart-lang/http#1 for details.
